# Generated by Django 2.2.7 on 2019-11-07 19:37

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts', verbose_name='изображение')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('publicate_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации')),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='коментатор')),
                ('text', models.TextField(blank=True, verbose_name='комментарий')),
                ('publicate_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='категория')),
            ],
        ),
    ]
